CREATE TABLE CONCESIONARIO (
cod NUMBER NOT NULL, 
nombre VARCHAR(15) NOT NULL, 
marca NUMBER NOT NULL, 
direccion VARCHAR(150) NOT NULL, 
telefono VARCHAR(15) , 
fecha_ina DATE NOT NULL,

CONSTRAINT PK_CONCESIONARIO PRIMARY KEY (cod)
);



CREATE TABLE MARCA (
id NUMBER NOT NULL, 
nombre VARCHAR(15) NOT NULL, 
concesionario_principal NUMBER,

CONSTRAINT PK_MARCA PRIMARY KEY (id),
CONSTRAINT FK_MARCA_CONCESIONARIO FOREIGN KEY (concesionario_principal) REFERENCES CONCESIONARIO(cod)
);

ALTER TABLE CONCESIONARIO DROP CONSTRAINT FK_CCONCESIONARIO_MARCA;

ALTER TABLE CONCESIONARIO ADD CONSTRAINT FK_CCONCESIONARIO_MARCA FOREIGN KEY (marca) REFERENCES MARCA(id) INITIALLY  DEFERRED;


CREATE TABLE MODELO (
marca NUMBER NOT NULL, 
modelo VARCHAR(15) NOT NULL, 
precio_recomendado NUMBER,

CONSTRAINT PK_MODELO PRIMARY KEY (marca, modelo),
CONSTRAINT FK_MODELO_MARCA FOREIGN KEY (marca) REFERENCES MARCA(id),
CONSTRAINT PRECIORECOMENDADOPOSITIVO CHECK (precio_recomendado >0)
);








CREATE TABLE CLIENTE( 
dni CHAR(9) NOT NULL,
nombre VARCHAR(20) NOT NULL,
direccion VARCHAR(150), 
telefono VARCHAR(15), 
cuenta_bancaria NUMBER(20) NOT NULL,

CONSTRAINT PK_CLIENTE PRIMARY KEY (dni)
);







CREATE TABLE CATALOGO( 
concesionario NUMBER NOT NULL,
marca NUMBER NOT NULL, 
modelo VARCHAR(15) NOT NULL,
precio_orientativo NUMBER, 
 
CONSTRAINT PK_CATALOGO PRIMARY KEY (concesionario, marca, modelo), 
CONSTRAINT PRECIOPOSITIVO CHECK (precio_orientativo >0), 
CONSTRAINT FK_CATALOGO_MODELO FOREIGN KEY (marca, modelo) REFERENCES MODELO(marca, modelo) ,
CONSTRAINT FK_CATALOGO_CONCESIONARIO FOREIGN KEY (concesionario) REFERENCES CONCESIONARIO(cod)

);






CREATE TABLE COCHE (
concesionario NUMBER,
marca NUMBER NOT NULL,
modelo VARCHAR(15) NOT NULL, 
numcoche NUMBER NOT NULL, 
color VARCHAR(15) NOT NULL, 
puertas NUMBER(1),                   
cilindrada NUMBER(4),

CONSTRAINT PK_COCHE PRIMARY KEY (numcoche),
CONSTRAINT NPUERTAS CHECK (puertas IN (3,5)),
CONSTRAINT FK_COCHE_CATALOGO FOREIGN KEY (marca, modelo,concesionario) REFERENCES CATALOGO(marca, modelo,concesionario),
);








CREATE TABLE VENDEDOR (
dni CHAR(9) NOT NULL, 
nombre VARCHAR(20) NOT NULL, 
telefono VARCHAR(15) NOT NULL, 
vendedor_jefe CHAR(9),
concesionario NUMBER NOT NULL,

CONSTRAINT PK_VENDEDOR PRIMARY KEY (dni),
CONSTRAINT FK_VENDEDOR_CONCESIONARIO FOREIGN KEY (concesionario) REFERENCES CONCESIONARIO(cod),
CONSTRAINT FK_VENDEDOR_JEFE FOREIGN KEY (vendedor_jefe) REFERENCES VENDEDOR(dni)

);


CREATE TABLE VENTA (
num NUMBER NOT NULL, 
coche NUMBER NOT NULL, 
cliente CHAR(9) NOT NULL, 
vendedor CHAR(9), 
fecha_venta DATE NOT NULL, 
pvp NUMBER,
matricula VARCHAR(8),

CONSTRAINT PK_VENTA PRIMARY KEY (num),
CONSTRAINT FK_VENTA_COHE FOREIGN KEY (coche) REFERENCES COCHE(numcoche),
CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (cliente) REFERENCES CLIENTE(dni),
CONSTRAINT FK_VENTA_VENDEDOR FOREIGN KEY (vendedor) REFERENCES VENDEDOR(dni),
CONSTRAINT PVPPOSITIVO CHECK (pvp >0) 
);
